apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy06
  labels:
    app: autodeploy06
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1718787169560
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy06
  template:
    metadata:
      labels:
        app: autodeploy06
    spec:
      containers:
        - name: autodeploy06
          image: acrworkflow1718787169560.azurecr.io/image-workflow-1718787169560:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
