apiVersion: v1
kind: Service
metadata:
  name: autodeploy06
  namespace: namespace-workflow-1718787169560
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: autodeploy06
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000